global using Microsoft.AspNetCore.Http;
global using Microsoft.Extensions.DependencyInjection;
global using MultiTenant.Core.Entities;
global using MultiTenant.Core.Entities.Interfaces;
global using MultiTenant.Core.Enums;
global using MultiTenant.Core.Repositories.Interfaces;
global using MultiTenant.Core.Services;
global using MultiTenant.Core.Services.Interfaces;
global using System.Linq.Expressions;
